DROP SCHEMA IF EXISTS errortracker CASCADE;

create SCHEMA errortracker;
use errortracker;

CREATE TABLE IF NOT EXISTS DEVELOPER(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GLUA_ERROR(
	`hash` VARCHAR(255) PRIMARY KEY,
	`count` INTEGER,
	`name` VARCHAR(255),
	short_err VARCHAR(255),
	stack TEXT,
	`state` SMALLINT
);
CREATE TABLE IF NOT EXISTS GLUA_ERROR_DEVELOPERS(
	ERRORS_HASH VARCHAR(255) NOT NULL,
	DEVELOPERS_ID BIGINT NOT NULL,
	FOREIGN KEY(`ERRORS_HASH`) REFERENCES GLUA_ERROR(`hash`),
	FOREIGN KEY(`DEVELOPERS_ID`) REFERENCES DEVELOPER(`id`)
);